services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - MARIADB_DATABASE=xettuyen2026
      - MARIADB_USER=admissions
      - MARIADB_PASSWORD=your_password
      - MARIADB_ROOT_PASSWORD=verysecret
    ports:
      - '13306:3306'